dataset_dir: '/home/ppeczek/Dokumenty/CityScapes-coarse'
gt_dir: 'gtCoarse'
examples_dir: 'leftImg8bit'
output_tfrecords_dir: 'tfrecords-full-size'
mapping_file: 'mappings.yaml'
destination_size: [2048, 1024]
binary_batch_size: 100
tfrecords_base_name: 'city-scapes.tfrecords'
max_workers: 24