mapping_file: '/home/ppeczek/Dokumenty/CityScapes/mappings.yaml'
destination_size: [2048, 1024]
model_name: 'ICNetV2'
num_classes: 20
model_dir: '/archive/model_storage/big_images_model/icnet_v2_first_2019_04_08_20:56'
checkpoint_name: 'checkpoint.ckpt-600'
gpu_to_use: 0
input_video: '/home/ppeczek/Dokumenty/CityScapes/video/converted_video/big_stuttgart_01.avi'
persist_video: True
output_video_file: '/home/ppeczek/Dokumenty/CityScapes/video/converted_video/infered_stuttgart_01.avi'