mode: 'val'
dataset_dir: '/home/ppeczek/Dokumenty/CityScapes'
tfrecords_dir: 'tfrecords-test-gen'
mapping_file: 'mappings.yaml'
tfrecords_base_name: 'city-scapes.tfrecords'
destination_size: [256, 128]
model_name: 'ThinModelV2'
num_classes: 20
model_dir: '/archive/model_storage/semantic_segmentation_expermient/single-gpu-stability-test_2019_03_13_05:36'
checkpoint_name: 'checkpoint.ckpt-1000'
batch_size: 45
dummy_iterator_tfrecords_files: 'all'
gpu_to_use: 0