mode: 'val'
task: 'auto-encoding' # 'segmentation'
dataset_dir: '/home/ppeczek/Dokumenty/CityScapes'
tfrecords_dir: 'tfrecords-full-size'
validation_examples_list: '/home/ppeczek/Dokumenty/CityScapes/val_list.csv'
mapping_file: 'mappings.yaml'
tfrecords_base_name: 'city-scapes.tfrecords'
destination_size: [2048, 1024]
model_name: 'ICNetAutoEncoder'
num_classes: 20
ignore_labels: [0]
model_dir: '/archive/model_storage/big_images_model/full_auto_encoding_big_holes_2019_09_08_16:20'
checkpoint_name: 'checkpoint.ckpt-13'
batch_size: 8
dummy_iterator_tfrecords_files: 'all'
gpu_to_use: 0